### ISSUE TITLE
Community Server?

### ISSUE THREAD

**Issue by HerkTG** [cosmograph-org/cosmos#1]
Hi Cosmograph team,

Do you have a Discord Server or plan to create one? I've recently stumbled on your project and have assigned one of our interns to explore the tool. She's planning on creating some content (sample project, video, and blog) integrating CosmosGraph and TigerGraph. Having an open communication channel (ie. Discord) would be Super helpful incase we run into snags. Alternatively you could join our Discord channel https://discord.gg/tigergraph. 

Cheers!
Jon Herke

**Comment by rokotyan** [comment]
Hi @HerkTG, great idea!

I've just created a new public Discord server, here is the invite link https://discord.gg/Rv8RUQuzsx.
