### ISSUE TITLE
graph nodes are in blury format and the labels are illegible

### ISSUE THREAD

**Issue by sadnzr** [cosmograph-org/cosmos#108]
Hello!
I use cosmograph in my app and unfortunately, tgraph nodes are in blury format and the labels are illegible , is this related to vga of the server?
or require the gpu module in production space?
![graph](https://github.com/cosmograph-org/cosmos/assets/165910168/5d33c304-c3d9-48ce-a85e-a4a6d1af34af)

**Comment by rokotyan** [comment]
@sadnzr Cosmograph relies on your machine's GPU, so it's probably an issue with your GPU itself or with the drivers. We've never seen such behavior before, can you provide with technical details of your GPU and OS?

**Comment by sadnzr** [comment]
my server does not have any GPU, it seems I must use GPU module explicitly! but is it possible to use good VGA card instead?

**Comment by rokotyan** [comment]
@sadnzr Can you please create an example on CodeSandbox or StackBlitz? That will enable us to take a look at the issue

**Comment by rokotyan** [comment]
Stale issue, closing
