### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Arnold1** [cosmograph-org/cosmos#12]
hi,

is there a way to visualize a decision tree - and import graphviz with dot format?
https://mljar.com/blog/visualize-decision-tree/

**Comment by rokotyan** [comment]
@Arnold1 We don't support the graphviz format, but if you translate your data into a javascript object with `nodes` and `links` arrays, you should be able to visualize your tree with Cosmos. Though, it won't like the pictures from the link you have shared.

**Comment by Arnold1** [comment]
what you mean by: ```Though, it won't like the pictures from the link you have shared.``` ?
