### ISSUE TITLE
Problem in combining the cosmos usage example into my own project.

### ISSUE THREAD

**Issue by sanbooo** [cosmograph-org/cosmos#15]
Thank you for developing this powerful tool and providing usage examples!

The aim of my project is to visualize a large medical network on a webpage. Thus, your package will be extremely helpful.

However, I have encountered a problem:
TS2305: Module '"C:/Users/22171/viz_web_project/mysite/frontend/node_modules/@cosmograph/cosmos/dist/index"' has no exported member 'GraphConfigInterface'.

Could you help me to solve it? I am totally new to typescript and web projects.

**Comment by rokotyan** [comment]
@sanbooo 
It's hard to tell from a single line error message. Probably it's related to your TypeScript configuration.

You can try using our CodeSandbox [example](https://codesandbox.io/s/cosmos-example-fmuf1x?file=/src/index.ts) as a boilerplate, or just use JavaScript.
