### ISSUE TITLE
Feature request: implement collision force to prevent overlap

### ISSUE THREAD

**Issue by jorrit-hdrn** [cosmograph-org/cosmos#18]
Hi there, 

First thank you for this great lib, the performance is outstanding!

I was wondering implementing the collision force of [D3-force](https://github.com/d3/d3-force#collision) is considered? 

I would like to use cosmos as a layout calculator with a different renderer, and for that I need a "prevent overlap" setting, which this force could provide. 

I would like to contribute although i'm not well versed in glsl. Would you say implementing this is feasible?

**Comment by rokotyan** [comment]
Hi @jorrit-hdrn,

It's not something we're currently working on, and it'll be difficult to implement on GPU without a significant performance loss. So, maybe one day but not in the nearest future 😔

**Comment by jorrit-hdrn** [comment]
Thank you for your message, that is too bad to hear! 

Could you shed some light on why it would lead to a significant performance loss? No worries if you're too busy.

**Comment by rokotyan** [comment]
@jorrit-hdrn Collision detection will require a lot of uncoalesced memory access operations (in finding the points that are overlapping in each simulation frame) which are very slow on GPUs. I guess there could be some tricks, but they are not obvious and the implementation won't be easy.
