### ISSUE TITLE
Feature request: same dataset should render the same layout

### ISSUE THREAD

**Issue by jorrit-hdrn** [cosmograph-org/cosmos#19]
Hi, 

Is there a way to specify the a "random seed", so that, given the same dataset twice,  the generated layout is the same?

Doing a quick scan over the repo I see quite some places random numbers are  inserted, so this might not be easy?

Thank you

**Comment by rokotyan** [comment]
@jorrit-hdrn Great question! Theoretically it's possible. We'll try and and let you know.

**Comment by rokotyan** [comment]
@jorrit-hdrn Version 1.3.0 will allow you to set a `randomSeed` value in the config! If you want to give it a try, you can already install `1.3.0-beta.0` which includes this change.
