### ISSUE TITLE
Missing dist folder in the published 1.3.0-beta.0

### ISSUE THREAD

**Issue by ilyabo** [cosmograph-org/cosmos#23]
Looks like publishing the last version didn't quite succeed. The `dist` folder is missing:

![image](https://user-images.githubusercontent.com/351828/208203175-36b40e56-c34d-4701-ad3b-30c64b484f90.png)

**Comment by rokotyan** [comment]
@ilyabo Thanks for reporting! Looks like I also forgot to use the beta tag for that release 🤦‍♂️

Anyway, there's a new version `1.3.0-beta.1` available now that has the issue fixed.

**Comment by ilyabo** [comment]
Cool, thanks Nikita!
