### ISSUE TITLE
Stylesheets / Open-Source Sample Projects

### ISSUE THREAD

**Issue by GenericP3rson** [cosmograph-org/cosmos#3]
Hello! I was wondering if you had any “style sheets”—or style templates for setting the configuration. Alternatively, if you could open-source the sample projects (other than the already open-sourced Sandbox) to be a point of reference for setting the configuration, that would be fantastic! Thanks!

**Comment by rokotyan** [comment]
@GenericP3rson Could you please tell a bit more about the problem you're trying to solve? The library itself has no pre-defined styles. The node and links colors can be provided in the configuration object. We have a palette that we use for Comsograph (https://cosmograph.app) but it's just a few colors.

**Comment by GenericP3rson** [comment]
Note: This question was answered on the Discord. Adding a summary below. Thank you, @rokotyan, for helping me out!

> Are there any stylesheets? 

There are not. The flow-y and sleek visualisations are defined by internal graph structures. 

> Are there any samples projects?

Yes, see below. However, the dashboard, known as Cosmograph, is closed-source.

MathWorks/Kuu
The MathWorks, Inc: symmetric positive definite matrix
https://sparse.tamu.edu/MathWorks/Kuu
https://cosmograph.app/run/?data=https://cosmograph.app/data/Kuu.csv

HB/blckhole
S CONNECTIVITY STRUCTURE OF A GEODESIC DOME ON A COARSE BASE
https://sparse.tamu.edu/HB/blckhole
https://cosmograph.app/run/?data=https://cosmograph.app/data/blckhole.csv

HB/can_229
SYMMETRIC PATTERN FROM CANNES,LUCIEN MARRO,JUNE 1981.
https://sparse.tamu.edu/HB/can_229
https://cosmograph.app/run/?data=https://cosmograph.app/data/can_229.csv
 
Gset/G34
2D torus, 40-by-50, uniformly random +1/-1 entries
https://sparse.tamu.edu/Gset/G34
https://cosmograph.app/run/?data=https://cosmograph.app/data/G34.csv

Pothen/sphere3
sphere3, with coordinates. From NASA, collected by Alex Pothen
https://sparse.tamu.edu/Pothen/sphere3
https://cosmograph.app/run/?data=https://cosmograph.app/data/sphere3.csv

Bydder/mri1
MRI reconstruction (1), from Mark Bydder, UCSD
https://sparse.tamu.edu/Bydder/mri1
https://cosmograph.app/run/?data=https://cosmograph.app/data/mri1.csv

Mittelmann/pds-90
Patient distribution (evacuation) system
https://sparse.tamu.edu/Mittelmann/pds-90
https://cosmograph.app/run/?data=https://cosmograph.app/data/pds-90.csv

Chen/pkustk10
PKU SYMMETRIC STIFFNESS, 4 TOWER SILO
https://sparse.tamu.edu/Chen/pkustk10
https://cosmograph.app/run/?data=https://cosmograph.app/data/pkustk10.csv

GHS_indef/aug3d
Gould, Hu, & Scott: expanded system-3D PDE (CUTEr)
https://sparse.tamu.edu/GHS_indef/aug3d
https://cosmograph.app/run/?data=https://cosmograph.app/data/aug3d.csv

Nasa/barth5
BARTH5: Nasa matrix, but with a diagonal added to the original matrix
https://sparse.tamu.edu/Nasa/barth5
https://cosmograph.app/run/?data=https://cosmograph.app/data/barth5.csv
[12:38 PM]
DIMACS10/delaunay_n10
DIMACS10 set: delaunay/delaunay_n10
https://sparse.tamu.edu/DIMACS10/delaunay_n10
https://cosmograph.app/run/?data=https://cosmograph.app/data/delaunay_n10.csv

HB/dwt_1005
SYMMETRIC CONNECTION TABLE FROM DTNSRDC, WASHINGTON
https://sparse.tamu.edu/HB/dwt_1005
https://cosmograph.app/run/?data=https://cosmograph.app/data/dwt_1005.csv

HB/gre_1107
UNSYMMETRIC MATRIX FROM GRENOBLE,FRANCOIS CACHARD,MARCH 1981.
https://sparse.tamu.edu/HB/gre_1107
https://cosmograph.app/run/?data=https://cosmograph.app/data/gre_1107.csv

Hollinger/jan99jac040sc
Jacobian from Bank of Canada ‘jan99’ model, oldstack 040, with scaling
https://sparse.tamu.edu/Hollinger/jan99jac040sc
https://cosmograph.app/run/?data=https://cosmograph.app/data/jan99jac040sc.csv

HB/man_5976
MANTEUFFEL’S FINITE ELEMENT PROBLEM (CONDENSED)
https://sparse.tamu.edu/HB/man_5976
https://cosmograph.app/run/?data=https://cosmograph.app/data/man_5976.csv

Boeing/msc01440
SYMMETRIC TEST MATRIX FROM MSC/NASTRAN CYLF8.OUT2
https://sparse.tamu.edu/Boeing/msc01440
https://cosmograph.app/run/?data=https://cosmograph.app/data/msc01440.csv

Nasa/nasa4704
STRUCTURE FROM NASA LANGLEY, 4704 DEGREES OF FREEDOM
https://sparse.tamu.edu/Nasa/nasa4704
https://cosmograph.app/run/?data=https://cosmograph.app/data/nasa4704.csv

Bai/rw5151
MARKOV CHAIN MODELING, RANDOM WALK (M = 100) G. W. STEWART
https://sparse.tamu.edu/Bai/rw5151
https://cosmograph.app/run/?data=https://cosmograph.app/data/rw5151.csv

Shyy/shyy41
Wei Shyy, Univ. Florida. CFD/Navier-Stokes,viscous flow, fully coupled
https://sparse.tamu.edu/Shyy/shyy41
https://cosmograph.app/run/?data=https://cosmograph.app/data/shyy41.csv

Shyy/shyy161
Wei Shyy, Univ. Florida. CFD/Navier-Stokes,viscous flow, fully coupled
https://sparse.tamu.edu/Shyy/shyy161
https://cosmograph.app/run/?data=https://cosmograph.app/data/shyy161.csv
[12:38 PM]
HB/young3c
real matrix from aero research, David Young, corrected RUA version
https://sparse.tamu.edu/HB/young3c
https://cosmograph.app/run/?data=https://cosmograph.app/data/young3c.csv

TKK/cyl6
Cylindrical shell, non-linear analysis, 3 RHS vectors at step 6. R Kouhia
https://sparse.tamu.edu/TKK/cyl6
https://cosmograph.app/run/?data=https://cosmograph.app/data/cyl6.csv

GHS_psdef/cvxbqp1
Gould, Hu, & Scott: barrier Hessian from convex QP (CUTEr)
https://sparse.tamu.edu/GHS_psdef/cvxbqp1
https://cosmograph.app/run/?data=https://cosmograph.app/data/cvxbqp1.csv
