### ISSUE TITLE
repulsionFromMouse doesn't seem to work

### ISSUE THREAD

**Issue by Leandro4002** [cosmograph-org/cosmos#31]
Hello,

I can't manage to get the `repulsionFromMouse` option to work.
I try to add this option on this sandbox but it doesn't work.
https://codesandbox.io/s/cosmos-usage-example-forked-cfloc1?file=/src/index.ts

Is there something I don't understand or it's not implemented ?

**Comment by Stukova** [comment]
@Leandro4002 Thanks for your question!

You have a working example!
We forgot to mention in the `repulsionFromMouse` description that the repulsion force is activated by pressing the right mouse button 🤦‍♀️.
