### ISSUE TITLE
set linkColor rgba

### ISSUE THREAD

**Issue by awaterho** [cosmograph-org/cosmos#42]
Hello, 

I'm trying to update the alpha values of edges by changing linkColor in the config, but it does not appear to work. I can set the alpha value on first load however. 

Ideally, I tried graph.setConfig({ linkColor: [128,128,178,.5] }); first, as well as by string "rbga(128,128,178.5)"

(Almost there, hopefully I can send a link to you tomorrow, when we have https working so you can see our application of cosmograph)

**Comment by Stukova** [comment]
Hi @awaterho! Thank you for your issue! We found the bug.  Fixing 🛠

**Comment by rokotyan** [comment]
@awaterho Fixed in `1.3.0-beta.3`
