### ISSUE TITLE
Device render problem

### ISSUE THREAD

**Issue by awaterho** [cosmograph-org/cosmos#49]
Of course Cosmograph is best experienced on a large monitor with nice graphics card, but still, some people are expecting to see at least a reduced version on other devices. 

Besides going out of memory (I realise that is a different and difficult issue!) we have seen two types of error, on creating the graph and setting the data. 

I guess these are more problems with regl than Cosmograph, but is there any plan to cope with these devices? 

**new Graph(canvas, config)**
(regl)  "OES_texture_float" extension is not supported by the current WebGL context, try upgrading your system or a different browser

**graph.current.setData(nodes, links)**
(regl) invalid width

**Comment by rokotyan** [comment]
@awaterho Unfortunately I don't think there's a way to resolve those issues:

* The "OES_texture_float" one most likely means that the GPU doesn't support floating point textures. But they are required to do the calculations;
* I'm not sure what the "invalid width" one exactly mean, but most likely it's also related to hardware.

Sometimes updating your browser and/or GPU drivers can help, but the only way to know is to try. Maybe if you can collect information about GPU types and browser versions from the affected users, we could do some investigation.

**Comment by awaterho** [comment]
happy to close this as 'wont fix' as i understand using the latest libraries is the way forward.

**Comment by awaterho** [comment]
Hey, I did go back to look at those "(regl) invalid width" issues, and found that I could not set the spaceSize to be 8192 in the cosmo config. Trying that, then catch the exception to reset spaceSize to 4096 means cosmograph will run happily on more devices

**Comment by rokotyan** [comment]
@awaterho Good point! We'll see what we can do about it.
