### ISSUE TITLE
Source code for cosmograph app run

### ISSUE THREAD

**Issue by mdav43** [cosmograph-org/cosmos#60]
Hi - I’m trying to quickly pilot this behind a corporate firewall and there is no ability to use the app and upload(even locally) Behind the firewall/w browser restrictions

suggest having a seperate repo where we can copy and run locally. 

I’ve copied from the code sandbox but can’t figure out how to get the external data from csv I have generated.

**Comment by rokotyan** [comment]
Hi @mdav43,

The code of Cosmograph.app is not open source and we're not planning to do it, at least for now.

Feel free to send us an email to hi@cosmograph.app if you want to discuss potential licensing.
