### ISSUE TITLE
Is a React Component possible?

### ISSUE THREAD

**Issue by steinmig** [cosmograph-org/cosmos#82]
Hi,

a quick question from a Javascript Noob.
Is there any major obstacle to write a React Component around your library to display your graph in a React webapp?

I would be interested in doing so, or even more favorable: to further translate the React component to a Dash component in order to go full Python with the rest of my webapp. How much effort do you think this would be?

Appreciate any guidance!

**Comment by rokotyan** [comment]
@steinmig We are currently testing the React integration in closed beta. If you'd like to give it a try, send us a note at hi@cosmograph.com!

I've never worked with Dash so I don't know how difficult it'll be, but we can try it.

**Comment by elliothershberg** [comment]
Hi @rokotyan, I just want to note I had a delivery failure when I tried emailing hi@cosmograph.com.

**Comment by steinmig** [comment]
@elliothershberg  The mail address in this issue is incorrect, the correct one is the one from the README:
hi@cosmograph.app

Please let me know if you happen to build a Dash component and get it to work. Unfortunately, I cannot find any time in the next two weeks.

**Comment by rokotyan** [comment]
My bad, thanks for providing the correct address @steinmig

**Comment by steinmig** [comment]
@rokotyan Is a react component available by now or why did you close the issue? Could you please point me to the right place in case one is available?

**Comment by rokotyan** [comment]
@rokotyan Yes, we hav it. You can check out the docs here https://cosmograph.app/docs/cosmograph/Cosmograph%20Library/Get%20Started

**Comment by steinmig** [comment]
Great thanks!
