### ISSUE TITLE
getNodePositions return incorrect positions

### ISSUE THREAD

**Issue by simCecca** [cosmograph-org/cosmos#9]
When I call the getNodePositions function, node positions are returned inconsistently with the visualization.

As an example, I took the coordinates and displayed them in Cytoscape, and as you can see, nodes have the same shape, but the ids are in different positions.

Taking the coordinates that the method returns and drawing them on paper, it comes something similar to Cytoscape.

It looks as if the mapping returned by the method returns the correct positions, but reverses the node ids

<img width="309" alt="Screenshot 2022-10-07 at 18 03 32" src="https://user-images.githubusercontent.com/19387429/194598063-068f05e6-364d-417f-9ddc-549665120e4c.png">

**Comment by rokotyan** [comment]
Version 1.1.1 containing this fix has been released and is available on NPM.

Release notes: https://github.com/cosmograph-org/cosmos/releases/tag/1.1.1
