### ISSUE TITLE
Can't get basic setup to work on a Vue application

### ISSUE THREAD

**Issue by marcodarko** [cosmograph-org/cosmos#99]
I don't know what is wrong because no errors occur also, here's a codebox of the basic setup:
https://codesandbox.io/p/devbox/gallant-forest-7vgq4z?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue

If you spot any errors or have any tips it would be much appreciated.

**Comment by rokotyan** [comment]
Can you please check if your example works, I'm getting this error when trying to open it
<img width="805" alt="image" src="https://github.com/cosmograph-org/cosmos/assets/755708/b26edfb7-7f27-4186-947f-4b4314d93ad7">

**Comment by marcodarko** [comment]
@rokotyan sorry about that, I forgot to make it public, [here's a new link](https://codesandbox.io/p/devbox/gallant-forest-7vgq4z?file=%2Fsrc%2Fcomponents%2FHelloWorld.vue&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clswcrnyq00073b6i07o05vot%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clswcrnyq00023b6id4932mfz%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clswcrnyq00043b6i07ocek2h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clswcrnyq00063b6id02h9z4j%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clswcrnyq00023b6id4932mfz%2522%253A%257B%2522id%2522%253A%2522clswcrnyq00023b6id4932mfz%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clswes34300023b6o5mjh8fq0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252Fcomponents%252FHelloWorld.vue%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clswes34300023b6o5mjh8fq0%2522%257D%252C%2522clswcrnyq00063b6id02h9z4j%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clswcrnyq00053b6ihja18jbu%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%2522%257D%255D%252C%2522id%2522%253A%2522clswcrnyq00063b6id02h9z4j%2522%252C%2522activeTabId%2522%253A%2522clswcrnyq00053b6ihja18jbu%2522%257D%252C%2522clswcrnyq00043b6i07ocek2h%2522%253A%257B%2522id%2522%253A%2522clswcrnyq00043b6i07ocek2h%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clswcrnyq00033b6imvle062e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522pnpm%2520run%2520dev%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clswcrnyq00033b6imvle062e%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A16.11607142857143%257D)

**Comment by rokotyan** [comment]
@marcodarko I think there might be a problem with the application setup itself. Even if I comment out all the Cosmograph-related code, it still doesn't work.

**Comment by marcodarko** [comment]
I think that site is having issues, let's try CodePen: https://codepen.io/marcodarko/pen/poYXWNj

**Comment by rokotyan** [comment]
Thanks @marcodarko 

Try changing `canvas` to `div` here:
<img width="444" alt="image" src="https://github.com/cosmograph-org/cosmos/assets/755708/7db815f5-9b95-44fc-a516-0ca8b53e23f9">

Looks like there is a typo in our docs. Thanks for bringing this to our attention.

**Comment by marcodarko** [comment]
Ah! perfect yeah I see the graph now! thanks!

**Comment by Stukova** [comment]
@marcodarko 

If the `fitViewOnInit` property is set to true (which is true by default), the `initialZoomLevel` value will be overridden. Additionally, if you call `cosmograph.setZoomLevel(5)` followed by `console.log(cosmograph.getZoomLevel())`, the zoom level displayed in the console will not be 5 because the zoom animation using d3's transition function will complete before the `getZoomLevel()` method reads the updated zoom level, even if the animation duration is 0.

For `initialZoomLevel` to have an effect, try to disable `fitViewOnInit` in the config.

**Comment by marcodarko** [comment]
@Stukova thank you so much for this info! Works great now! Really appreciate your help.
Perhaps I would suggest I would prefer the opposite the behavior, that my user setting would override the default, but it's a minor suggestion for consideration.
